version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:13.0
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - untitled_game_data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:6.0.8
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
  accounts:
    container_name: accounts
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    volumes:
      - ./core:/server/core
      - ./proto:/server/proto
      - ./accounts:/server/accounts
      - ./cmd/accounts:/server/cmd
      - ./config/accounts:/server/config
      - ./migrations/accounts:/server/migrations
volumes:
  untitled_game_data:
