version: "3.8"

services:
  nginx:
    image: nginx:1.19.4
    ports:
      - "4000:4000"
    depends_on:
      - accounts
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  postgres:
    image: postgres:13.0
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - untitled_game_data:/var/lib/postgresql/data
  redis:
    image: redis:6.0.8
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
  accounts:
    build:
      context: .
    expose:
      - "8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./core:/server/core
      - ./accounts:/server/accounts
      - ./cmd/accounts:/server/cmd
      - ./config/accounts:/server/config
      - ./migrations/accounts:/server/migrations
volumes:
  untitled_game_data:
